# Generated by Django 5.0.6 on 2024-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarization',
            name='summary',
            field=models.CharField(default='default summary', max_length=2000),
        ),
        migrations.AlterField(
            model_name='summarization',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
