# Generated by Django 5.0.6 on 2024-06-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_summarization_summary_alter_summarization_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarization',
            name='summary',
            field=models.TextField(default='default summary'),
        ),
        migrations.AlterField(
            model_name='summarization',
            name='text',
            field=models.TextField(),
        ),
    ]
