# Generated by Django 5.0.6 on 2024-06-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_summarization_summary_alter_summarization_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('summary', models.TextField(default='default summary')),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
    ]
