# Generated by Django 5.0.6 on 2024-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_audio_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
    ]
