# Generated by Django 5.0.6 on 2024-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_powerpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('summary', models.TextField(null=True)),
                ('audio', models.FileField(upload_to='audio/')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
