# Generated by Django 5.0.6 on 2024-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='/home/ahmed/myGraduationProject/myapp/ai/Easy_Wav2Lip/test_audio1_Easy-Wav2Lip.mp4', upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
